name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs: 
  MSVC: 
    runs-on: windows-latest
    name: MSVC Build Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup python
        uses: actions/setup-python@v5
        with:
            python-version: '3.13'

      - name: Install build requirements
        run: python -m pip install meson ninja

      - name: Configure Build
        run: meson setup builddir -Dbuild_tests=True -Dvsenv=True

      - name: Build
        run: meson compile -C builddir

      - name: Test
        run: meson test -C builddir -vv

  Intel_Win: 
    runs-on: windows-latest
    name: Intel-Win
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: intel
          python-version: 3.13

      - name: Install build requirements
        run: conda install --yes -c conda-forge meson ninja dpcpp_win-64
            

      - name: Configure Build
        run: |
            meson setup builddir -Dbuild_tests=True
        env:
          CXX: icpx

      - name: Build
        run: meson compile -C builddir

      - name: Test
        run: meson test -C builddir -vv

  GNU_UBUNTU:
    name: G++ on ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install GNU compiler
        run: sudo apt install g++-14

      - name: Setup python
        uses: actions/setup-python@v5
        with:
            python-version: '3.13'

      - name: Install build requirements
        run: python -m pip install meson ninja

      - name: Configure Build
        run: meson setup builddir -Dbuild_tests=True
        env:
          CXX: g++-14

      - name: Build
        run: meson compile -C builddir

      - name: Test
        run: meson test -C builddir -vv

  LLVM_UBUNTU:
    name: LLVM on ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install LLVM compiler
        run: sudo apt install clang-18

      - name: Setup python
        uses: actions/setup-python@v5
        with:
            python-version: '3.13'

      - name: Install build requirements
        run: python -m pip install meson ninja

      - name: Configure Build
        run: meson setup builddir -Dbuild_tests=True
        env:
          CXX: clang++-18

      - name: Build
        run: meson compile -C builddir

      - name: Test
        run: meson test -C builddir -vv

  INTEL_UBUNTU:
    name: Intel on ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: intel
          python-version: 3.13

      - name: Install build requirements
        run: conda install --yes -c conda-forge meson ninja dpcpp_linux-64

      - name: Configure Build
        run: meson setup builddir -Dbuild_tests=True
        env:
          CXX: icpx

      - name: Build
        run: meson compile -C builddir

      - name: Test
        run: meson test -C builddir -vv

  GNU_MAC:
    name: G++ on MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install GNU compiler
        run: brew install gcc@15

      - name: Setup python
        uses: actions/setup-python@v5
        with:
            python-version: '3.13'

      - name: Install build requirements
        run: python -m pip install meson ninja

      - name: Configure Build
        run: meson setup builddir -Dbuild_tests=True
        env:
          CXX: g++-15

      - name: Build
        run: meson compile -C builddir

      - name: Test
        run: meson test -C builddir -vv

  LLVM_MAC:
    name: LLVM on MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install LLVM compiler
        run: brew install llvm@20 lld@20

      - name: Setup python
        uses: actions/setup-python@v5
        with:
            python-version: '3.13'

      - name: Install build requirements
        run: python -m pip install meson ninja

      - name: Configure Build
        run: meson setup builddir -Dbuild_tests=True
        env:
          CXX: /opt/homebrew/opt/llvm/bin/clang++

      - name: Build
        run: meson compile -C builddir

      - name: Test
        run: meson test -C builddir -vv


           
        