name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs: 
  MSVC: 
    runs-on: windows-latest
      name: MSVC Build Test
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            persist-credentials: false

        - name: Setup python
          uses: actions/setup-python@v5
          with:
              python-version: '3.13'

        - name: Install build requirements
          run: python -m pip install meson ninja

        - name: Configure Build
          run: meson setup build -Dbuild_tests=True

        - name: Build and Run tests
          run: meson test -C build
           
        