name: Test CPP builds

on:
  pull_request:
  push:
    branches:
      - main

jobs: 
  MSVC: 
    runs-on: windows-latest
    name: MSVC Build Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install build requirements
        run: pipx install meson

      - name: Configure Build
        run: meson setup builddir -Dtests=True -Dvsenv=True
        env:
          CXX: cl
          CC: cl

      - name: List Build Targets
        run: |
            meson compile -C builddir -v subprojects/highway/hwy_list_targets
            builddir/subprojects/highway/hwy_list_targets

      - name: Build
        run: meson compile -C builddir -v

      - name: Test
        run: meson test -C builddir -vv

  Intel_Win: 
    runs-on: windows-latest
    name: Intel compiler on Windows
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: intel
          python-version: 3.13

      - name: Install build requirements
        run: conda install --yes -c conda-forge meson ninja dpcpp_win-64=2025.1 pkg-config

      - name: Append to LIB and LIBRARY_PATH
        run: |
          "LIB=$env:CONDA_PREFIX\Library\lib;$env:LIB" >> $env:GITHUB_ENV
          "LIBRARY_PATH=$env:CONDA_PREFIX\Library\lib;$env:LIBRARY_PATH" >> $env:GITHUB_ENV

        # Appending conda's library path to the LIB and LIBRARY_PATH environment variables...
      - name: Configure Build
        run: |
            echo $env:LIB
            echo $env:LIBRARY_PATH
            meson setup builddir -Dtests=True -Dvsenv=True
        env:
          CXX: icx-cl
          CC: icx-cl

      - name: List Build Targets
        run: |
            meson compile -C builddir -v subprojects/highway/hwy_list_targets
            builddir/subprojects/highway/hwy_list_targets

      - name: Build
        run: |
            meson compile -C builddir -v

      - name: Test
        run: meson test -C builddir -vv

  CLANG_Win:
    runs-on: windows-latest
    name: LLVM on Windows
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install build requirements
        run: pipx install meson

      - name: Configure Build
        run: meson setup builddir -Dtests=True -Dvsenv=True
        env:
          CXX: clang-cl
          CC: clang-cl

      - name: List Build Targets
        run: |
            meson compile -C builddir -v subprojects/highway/hwy_list_targets
            builddir/subprojects/highway/hwy_list_targets

      - name: Build
        run: meson compile -C builddir -v

      - name: Test
        run: meson test -C builddir -vv
  
  GNU_UBUNTU:
    name: G++ on ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install GNU compiler
        run: sudo apt install g++-14

      - name: Install build requirements
        run: pipx install meson

      - name: Configure Build
        run: meson setup builddir -Dtests=True
        env:
          CXX: g++-14

      - name: List Build Targets
        run: |
            meson compile -C builddir -v subprojects/highway/hwy_list_targets
            builddir/subprojects/highway/hwy_list_targets

      - name: Build
        run: meson compile -C builddir -v -j 1

      - name: Test
        run: meson test -C builddir -vv

  LLVM_UBUNTU:
    name: LLVM on ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install LLVM compiler
        run: sudo apt install clang-18

      - name: Install build requirements
        run: pipx install meson

      - name: Configure Build
        run: meson setup builddir -Dtests=True
        env:
          CXX: clang++-18
          CC: clang-18

      - name: List Build Targets
        run: |
            meson compile -C builddir -v subprojects/highway/hwy_list_targets
            builddir/subprojects/highway/hwy_list_targets

      - name: Build
        run: meson compile -C builddir -v

      - name: Test
        run: meson test -C builddir -vv

  INTEL_UBUNTU:
    name: Intel on ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: intel
          python-version: 3.13

      - name: Install build requirements
        run: conda install --yes -c conda-forge meson ninja dpcpp_linux-64=2025.1

      - name: Conda Environment info
        run: |
          conda info
          conda list

      - name: Configure Build
        run: meson setup builddir -Dtests=True
        env:
          CXX: icx
          CC: icx
          LDFLAGS: -lpthread

      - name: List Build Targets
        run: |
            meson compile -C builddir -v subprojects/highway/hwy_list_targets
            builddir/subprojects/highway/hwy_list_targets

      - name: Build
        run: meson compile -C builddir -v

      - name: Test
        run: meson test -C builddir -vv

  GNU_MAC:
    name: G++ on MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install GNU compiler
        run: brew install gcc@15

      - name: Install build requirements
        run: pipx install meson

      - name: Configure Build
        run: meson setup builddir -Dtests=True
        env:
          CXX: g++-15
          CC: gcc-15

      - name: List Build Targets
        run: |
            meson compile -C builddir -v subprojects/highway/hwy_list_targets
            builddir/subprojects/highway/hwy_list_targets

      - name: Build
        run: meson compile -C builddir -v

      - name: Test
        run: meson test -C builddir -vv

  APPLE_LLVM:
    name: Apple LLVM
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install build requirements
        run: pipx install meson

      - name: Configure Build
        run: meson setup builddir -Dtests=True

      - name: List Build Targets
        run: |
            meson compile -C builddir -v subprojects/highway/hwy_list_targets
            builddir/subprojects/highway/hwy_list_targets

      - name: Build
        run: meson compile -C builddir -v

      - name: Test
        run: meson test -C builddir -vv

  LLVM_MAC:
    name: LLVM on MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install LLVM compiler
        run: brew install llvm@20 lld@20

      - name: Install build requirements
        run: pipx install meson

      - name: Configure Build
        run: meson setup builddir -Dtests=True
        env:
          CXX: /opt/homebrew/opt/llvm/bin/clang++
          CC: /opt/homebrew/opt/llvm/bin/clang

      - name: List Build Targets
        run: |
            meson compile -C builddir -v subprojects/highway/hwy_list_targets
            builddir/subprojects/highway/hwy_list_targets

      - name: Build
        run: meson compile -C builddir -v

      - name: Test
        run: meson test -C builddir -vv


           
        